### ISSUE TITLE
Luxendo metadata not recognized

### ISSUE THREAD

**Issue by cikus3** [bigdataprocessor/bigdataprocessor2#186] opened 2022-02-02 16:46 UTC
Hi Christian, all good with BDP2, but a few notes: when opening the Luxendo data, Voxel size is lost and needs to be re-set (using "set voxel size"); a few versions agao,  it was working.. Any way can it be fixed? Thanks!  I attach screen shot of current medata file; I can send you the originla data if necessary
![image](https://user-images.githubusercontent.com/35956783/152197969-59c9a68e-3e37-4902-bf40-61f3f7e75c12.png)
![image](https://user-images.githubusercontent.com/35956783/152198305-b0073d06-3b40-41b3-b11e-f89067d0764d.png)

**Comment by tischi** [comment] 2022-02-06 15:12
@cikus3 

The issue is that BDP2 currently is reading the pixel size from the HDF5 file and _not_ from the JSON file.

Could you please download [HDFView](https://www.hdfgroup.org/downloads/hdfview/) and open one of the HDF5 files and check whether the data has the "element_size_um" attribute?

<img width="652" alt="image" src="https://user-images.githubusercontent.com/2157566/152687435-6fa79386-0eec-41f2-8ffc-30e478dc7669.png">
 
That's how I currently read it:

```
    public static boolean setVoxelSizeFromLuxendoHDF5( IHDF5Reader reader, FileInfos fileInfos )
    {
        if ( reader.hasAttribute( "/" + fileInfos.h5DataSetName, "element_size_um" ) )
        {
            final double[] voxelSizeZYX = reader.float64().getArrayAttr( "/" + fileInfos.h5DataSetName, "element_size_um");
            double[] voxelSizeXYZ = new double[ 3 ];

            // reorder the dimensions
            for ( int d = 0; d < 3; d++ )
                voxelSizeXYZ[ d ] = voxelSizeZYX[ 2 - d];

            fileInfos.voxelUnit = "micrometer";
            fileInfos.voxelSize = voxelSizeXYZ;

            return true;
        }
        else
        {
            return false;
        }
    }
```

**Comment by tischi** [comment] 2022-02-06 15:17
...and please could you send me one of the JSON files?
Is there one for each time point or just one per folder?

**Comment by janroden** [comment] 2022-02-08 10:28
Hi @cikus3 and @tischi ,

For the Luxendo images, the voxel size should be in both places, the `element_size_um` attribute of the respective H5 dataset (from where BDP2 currently reads it), as well as in the `Cam_XXX_00000.json` file, in the field `processingInformation` > `voxel_size_um`. The JSON file currently normally only exists for the first time point. But all the JSON metadata are *also* inside each H5 file, in a dataset called `metadata`, for all time points. In all these three places, the voxel size should be the same, and have the same width-height-depth order.

Yes, it would be great if you could post one of the JSON files here, or check that it contains the correct voxel size in `processingInformation` > `voxel_size_um`. And if that's correct, then as @tischi described, please use HDFView to check that it is also correct in the `element_size_um` H5 attribute. 

Thank you!

**Comment by tischi** [comment] 2022-02-08 16:44
@janroden I have here some other data where the voxel size seems to be in the order `x,y,z` and not `z,y,x` as it should be given the data set dimensions. Do you have any idea how that could have happened (I do not remember now who gave me that data...)?

<img width="793" alt="image" src="https://user-images.githubusercontent.com/2157566/153034010-7b1361c8-4569-4ed4-8b94-fdf8ede44252.png">

@bon

**Comment by tischi** [comment] 2022-02-08 16:51
@cikus3 I think I found the bug, could you please update Fiji and see whether it can now read the voxel size?

**Comment by janroden** [comment] 2022-02-08 20:40
Thanks for posting the metadata!
Ah yes, what I wrote above was incorrect: actually, in the H5 attribute `element_size_um`, the order is depth-height-width, and in the JSON metadata it's the reverse, i.e., width-height-depth.

**Comment by janroden** [comment] 2022-02-08 20:42
> @janroden I have here some other data where the voxel size seems to be in the order `x,y,z` and not `z,y,x` as it should be given the data set dimensions. Do you have any idea how that could have happened (I do not remember now who gave me that data...)?
> 
> <img alt="image" width="793" src="https://user-images.githubusercontent.com/2157566/153034010-7b1361c8-4569-4ed4-8b94-fdf8ede44252.png">

Hm, maybe this is some old image that had a metadata bug? I just checked in the current code and there the order in `element_size_um` is depth-height-width (i.e. z, y, x).

**Comment by cikus3** [comment] 2022-02-14 16:21
I can now open the Luxensdo data with the correct voxel size! On my side, you can close the Issue; thanks!

**Closed** 2022-02-15 07:44 UTC
